# Generated by Django 6.0.3 on 2026-03-19 20:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_envio', models.CharField(choices=[('SHALOM', 'shalom'), ('DELIVERY', 'delivery'), ('OTRA_AGENCIA', 'otra_agencia')], default='SHALOM', max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('departamento', models.CharField(choices=[('AMAZONAS', 'Amazonas'), ('ANCASH', 'Áncash'), ('APURIMAC', 'Apurímac'), ('AREQUIPA', 'Arequipa'), ('AYACUCHO', 'Ayacucho'), ('CAJAMARCA', 'Cajamarca'), ('CALLAO', 'Callao'), ('CUSCO', 'Cusco'), ('HUANCAVELICA', 'Huancavelica'), ('HUANUCO', 'Huánuco'), ('ICA', 'Ica'), ('JUNIN', 'Junín'), ('LA_LIBERTAD', 'La Libertad'), ('LAMBAYEQUE', 'Lambayeque'), ('LIMA', 'Lima'), ('LORETO', 'Loreto'), ('MADRE_DE_DIOS', 'Madre de Dios'), ('MOQUEGUA', 'Moquegua'), ('PASCO', 'Pasco'), ('PIURA', 'Piura'), ('PUNO', 'Puno'), ('SAN_MARTIN', 'San Martín'), ('TACNA', 'Tacna'), ('TUMBES', 'Tumbes'), ('UCAYALI', 'Ucayali')], default='LIMA', max_length=20)),
                ('agencia_destino', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('numero_pedido', models.PositiveIntegerField(editable=False)),
                ('monto_inicial', models.IntegerField(blank=True, default=0, null=True)),
                ('monto_final', models.IntegerField(blank=True, default=0, null=True)),
                ('restante', models.IntegerField(default=0)),
                ('clave', models.CharField(max_length=4)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.campana')),
                ('producto_asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
        ),
    ]
