# Generated by Django 6.0.3 on 2026-03-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='procesado_inventario',
            field=models.BooleanField(default=False),
        ),
    ]
