# Generated by Django 6.0.3 on 2026-03-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_cliente_procesado_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado_envio',
            field=models.CharField(choices=[('POR_ENVIAR', 'Por enviar'), ('EN_TRANSITO', 'En transito'), ('LLEGO_FALTA_PAGAR', 'Llego pero falta pagar'), ('CANCELADO', 'Cancelado')], default='POR_ENVIAR', max_length=20),
        ),
    ]
