# Generated by Django 6.0.3 on 2026-03-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_cliente_estado_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='regalo',
            field=models.BooleanField(default=False),
        ),
    ]
