# Generated by Django 6.0.3 on 2026-03-19 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('operaciones', '0005_cliente_regalo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='productos',
            field=models.ManyToManyField(to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='campana',
            name='trabajador_asignado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
