# Generated by Django 6.0.3 on 2026-03-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0006_campana_productos_campana_trabajador_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='registrado_agencia',
            field=models.BooleanField(default=False),
        ),
    ]
