# Generated by Django 6.0.3 on 2026-03-20 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0007_cliente_registrado_agencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='registrado_agencia',
        ),
    ]
