# Generated by Django 6.0.3 on 2026-03-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0008_remove_cliente_registrado_agencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado_envio',
            field=models.CharField(choices=[('POR_ENVIAR', 'Por enviar'), ('EN_TRANSITO', 'En transito'), ('LLEGO_FALTA_PAGAR', 'Llego pero falta pagar'), ('CANCELADO', 'Cancelado'), ('RETORNO', 'Retorno')], default='POR_ENVIAR', max_length=20),
        ),
    ]
